name: Render and publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-org/quarto-actions/setup@v2
        with:
          quarto-version: '1.5.57'  # specify the Quarto version

      - name: Set working directory
        run: |
          mkdir -p Exercises/_site
        working-directory: Exercises

      - name: Render Quarto documents
        run: |
          quarto render Exercises/*.qmd --to html
        working-directory: Exercises

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site/'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./Exercises/_site

